export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECIEVE_AUTH = 'RECIEVE_AUTH';
export const FETCH_AUTH_FAILED = 'FETCH_AUTH_FAILED';
export const RECIEVE_USER_DATA = 'RECIEVE_USER_DATA';
